#include <SDL3/SDL.h>
#include <stdio.h>
#include <stddef.h>
#define V(name) printf("#define S3_%s 0x%llx\n", &#name[4], (unsigned long long)(name));
#define O(type, member, alias) printf("#define S3_OFF_%s %zu\n", alias, offsetof(type, member));
int main(void){
 printf("/* generated from SDL 3.4.16 headers (port/switch/tools/sdl3_values_probe.c); do not edit */\n");
 V(SDL_INIT_AUDIO) V(SDL_INIT_VIDEO) V(SDL_INIT_JOYSTICK) V(SDL_INIT_HAPTIC) V(SDL_INIT_GAMEPAD) V(SDL_INIT_EVENTS)
 V(SDL_EVENT_QUIT) V(SDL_EVENT_WINDOW_FOCUS_GAINED) V(SDL_EVENT_WINDOW_FOCUS_LOST) V(SDL_EVENT_WINDOW_CLOSE_REQUESTED)
 V(SDL_EVENT_WINDOW_RESIZED) V(SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED) V(SDL_EVENT_KEY_DOWN) V(SDL_EVENT_KEY_UP)
 V(SDL_EVENT_GAMEPAD_ADDED) V(SDL_EVENT_GAMEPAD_REMOVED)
 V(SDL_GL_RED_SIZE) V(SDL_GL_GREEN_SIZE) V(SDL_GL_BLUE_SIZE) V(SDL_GL_ALPHA_SIZE) V(SDL_GL_BUFFER_SIZE) V(SDL_GL_DOUBLEBUFFER)
 V(SDL_GL_DEPTH_SIZE) V(SDL_GL_STENCIL_SIZE) V(SDL_GL_MULTISAMPLEBUFFERS) V(SDL_GL_MULTISAMPLESAMPLES)
 V(SDL_GL_CONTEXT_MAJOR_VERSION) V(SDL_GL_CONTEXT_MINOR_VERSION) V(SDL_GL_CONTEXT_FLAGS) V(SDL_GL_CONTEXT_PROFILE_MASK)
 V(SDL_GL_FRAMEBUFFER_SRGB_CAPABLE)
 V(SDL_GL_CONTEXT_PROFILE_CORE) V(SDL_GL_CONTEXT_PROFILE_COMPATIBILITY) V(SDL_GL_CONTEXT_PROFILE_ES) V(SDL_GL_CONTEXT_DEBUG_FLAG)
 V(SDL_WINDOW_FULLSCREEN) V(SDL_WINDOW_OPENGL) V(SDL_WINDOW_HIDDEN) V(SDL_WINDOW_RESIZABLE) V(SDL_WINDOW_HIGH_PIXEL_DENSITY)
 V(SDL_GAMEPAD_BUTTON_SOUTH) V(SDL_GAMEPAD_BUTTON_EAST) V(SDL_GAMEPAD_BUTTON_WEST) V(SDL_GAMEPAD_BUTTON_NORTH)
 V(SDL_GAMEPAD_BUTTON_BACK) V(SDL_GAMEPAD_BUTTON_GUIDE) V(SDL_GAMEPAD_BUTTON_START) V(SDL_GAMEPAD_BUTTON_LEFT_STICK)
 V(SDL_GAMEPAD_BUTTON_RIGHT_STICK) V(SDL_GAMEPAD_BUTTON_LEFT_SHOULDER) V(SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER)
 V(SDL_GAMEPAD_BUTTON_DPAD_UP) V(SDL_GAMEPAD_BUTTON_DPAD_DOWN) V(SDL_GAMEPAD_BUTTON_DPAD_LEFT) V(SDL_GAMEPAD_BUTTON_DPAD_RIGHT)
 V(SDL_GAMEPAD_BUTTON_COUNT)
 V(SDL_GAMEPAD_AXIS_LEFTX) V(SDL_GAMEPAD_AXIS_LEFTY) V(SDL_GAMEPAD_AXIS_RIGHTX) V(SDL_GAMEPAD_AXIS_RIGHTY)
 V(SDL_GAMEPAD_AXIS_LEFT_TRIGGER) V(SDL_GAMEPAD_AXIS_RIGHT_TRIGGER) V(SDL_GAMEPAD_AXIS_COUNT)
 V(SDL_GAMEPAD_TYPE_UNKNOWN) V(SDL_GAMEPAD_TYPE_STANDARD) V(SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO)
 V(SDL_AUDIO_U8) V(SDL_AUDIO_S16LE) V(SDL_AUDIO_S32LE) V(SDL_AUDIO_F32LE) V(SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK)
 printf("#define S3_EVENT_SIZE %zu\n", sizeof(SDL_Event));
 printf("#define S3_AUDIOSPEC_SIZE %zu\n", sizeof(SDL_AudioSpec));
 O(SDL_CommonEvent, type, "TYPE") O(SDL_CommonEvent, timestamp, "TIMESTAMP")
 O(SDL_WindowEvent, windowID, "WINDOW_ID") O(SDL_WindowEvent, data1, "WINDOW_DATA1") O(SDL_WindowEvent, data2, "WINDOW_DATA2")
 O(SDL_GamepadDeviceEvent, which, "GAMEPAD_WHICH")
 O(SDL_AudioSpec, format, "SPEC_FORMAT") O(SDL_AudioSpec, channels, "SPEC_CHANNELS") O(SDL_AudioSpec, freq, "SPEC_FREQ")
 printf("#define S3_SIZEOF_AUDIOFORMAT %zu\n", sizeof(SDL_AudioFormat));
 return 0;}
